# Generated by Django 5.2.7 on 2025-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_age', models.IntegerField()),
                ('Employee_email', models.EmailField(max_length=254, unique=True)),
                ('Employee_salary', models.IntegerField()),
                ('Employee_mobile', models.BigIntegerField()),
                ('Employee_department', models.CharField(max_length=50)),
                ('Employee_join_date', models.DateField()),
            ],
        ),
    ]
